# Auto-detect Qt 6 MinGW and matching toolchain on Windows (first configure only).
if(NOT WIN32)
  return()
endif()

if(CMAKE_PREFIX_PATH)
  return()
endif()

file(GLOB _qt_versions LIST_DIRECTORIES true "C:/Qt/6.*")
list(SORT _qt_versions COMPARE NATURAL ORDER DESCENDING)
foreach(_ver IN LISTS _qt_versions)
  if(EXISTS "${_ver}/mingw_64/lib/cmake/Qt6/Qt6Config.cmake")
    set(CMAKE_PREFIX_PATH "${_ver}/mingw_64" CACHE PATH "Qt 6 prefix (auto-detected)" FORCE)
    message(STATUS "Auto-detected Qt: ${_ver}/mingw_64")
    break()
  endif()
endforeach()

if(NOT CMAKE_CXX_COMPILER OR CMAKE_CXX_COMPILER STREQUAL "CMAKE_CXX_COMPILER-NOTFOUND")
  file(GLOB _mingw_roots LIST_DIRECTORIES true "C:/Qt/Tools/mingw*")
  list(SORT _mingw_roots COMPARE NATURAL ORDER DESCENDING)
  foreach(_root IN LISTS _mingw_roots)
    if(EXISTS "${_root}/bin/g++.exe")
      set(CMAKE_C_COMPILER "${_root}/bin/gcc.exe" CACHE FILEPATH "MinGW gcc (auto-detected)" FORCE)
      set(CMAKE_CXX_COMPILER "${_root}/bin/g++.exe" CACHE FILEPATH "MinGW g++ (auto-detected)" FORCE)
      message(STATUS "Auto-detected MinGW: ${_root}/bin")
      break()
    endif()
  endforeach()
endif()
